### ISSUE TITLE
security issue - clients can add server

### ISSUE THREAD

**Issue by sjanecki** [faye/faye-cluster-node#1]
Client (in a webbrowser) can publish and listen do /faye/cluster/*

this is very bad because client can add his own 'man in the middle' server
those messages shoud stay on the 'server side'

BTW. faye is great! keep it up!

**Comment by jcoglan** [comment]
Sorry I didn't reply to this at the time; this repo was just a quick hack and I'm not committing to fixing issues or making it production-ready. If I ever pick it up again I'll revisit this issue.
