### ISSUE TITLE
bug with disconnected servers

### ISSUE THREAD

**Issue by sjanecki** [faye/faye-cluster-node#2]
lets say that I have cluster with 3 faye-cluster servers A, B and C.

When I killed for example server C, server A and B didnt deleted server C from _connections array.
Could you fix this?

There are two scenarios. 
1. Server C gracefully send disconnect message
2. Server C was killed (didnt send disconnect message) and server A and B cant connect to server C

thanks!

**Comment by jcoglan** [comment]
Sorry I didn't reply to this at the time; this repo was just a quick hack and I'm not committing to fixing issues or making it production-ready. If I ever pick it up again I'll revisit this issue.
